# Generated by Django 5.2.6 on 2025-09-10 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='field1',
            field=models.FileField(default='asd', upload_to='media/products/'),
        ),
    ]
