# Generated by Django 5.2.6 on 2025-09-10 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_field1'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='emailfield',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
