# Generated by Django 5.2.6 on 2025-09-10 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_emailfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='datefield',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='datetimefield',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='field3',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='field4',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ip_field',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
