# Generated by Django 5.2.6 on 2025-09-09 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('description', models.TextField()),
                ('author_first_name', models.CharField(max_length=30)),
                ('author_last_name', models.CharField(blank=True, max_length=25)),
                ('created_date', models.DateTimeField()),
            ],
        ),
    ]
