# Generated by Django 5.2.6 on 2025-09-10 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_modified_date_alter_article_created_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='articleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
    ]
