# Generated by Django 5.2.6 on 2025-09-10 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_article_article_category_alter_articlecategory_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecategory',
            name='created_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
