# Generated by Django 5.2.6 on 2025-09-10 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_articlecategory_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_category',
        ),
        migrations.AddField(
            model_name='article',
            name='article_category',
            field=models.ManyToManyField(blank=True, to='articles.articlecategory'),
        ),
    ]
