# Generated by Django 5.2.6 on 2025-09-10 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_remove_article_article_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='articleUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25, verbose_name='İsim')),
                ('last_name', models.CharField(max_length=25, verbose_name='Soy İsim')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.articleuser', verbose_name='Yazar'),
        ),
    ]
