# Generated by Django 5.2.6 on 2025-09-11 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_articleuser_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleuser',
            name='gender',
            field=models.CharField(choices=[('e', 'Erkek'), ('k', 'Kadın'), ('b', 'Belirtmek İstemiyorum')], default='b', max_length=1),
        ),
    ]
