# Generated by Django 5.2.6 on 2025-09-11 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_articleuser_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleuser',
            name='age',
            field=models.IntegerField(choices=[(1, 12), (1, 13)], default=1),
        ),
    ]
