# Generated by Django 5.2.6 on 2025-09-11 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_articleuser_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articleuser',
            name='age',
        ),
        migrations.AlterModelTable(
            name='article',
            table='Makaleler',
        ),
    ]
