# Generated by Django 5.2.6 on 2025-09-11 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_remove_articleuser_age_alter_article_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Makale', 'verbose_name_plural': 'Makaleler'},
        ),
    ]
