# Generated by Django 5.2.6 on 2025-09-11 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_alter_article_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('created_date',), 'verbose_name': 'Makale', 'verbose_name_plural': 'Makaleler'},
        ),
    ]
